---
# Source: hivemq-operator/templates/global/hivemq-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hivemq-operator-hivemq-psp
  labels:
    app: hivemq-operator
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
      - hivemq-operator
