---
# Source: hivemq-edge/templates/configmap_configuration.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    helm.sh/chart: hivemq-edge-0.1.0
    app.kubernetes.io/name: "hivemq-edge"
    app.kubernetes.io/instance: "my-platform"
    app.kubernetes.io/version: "2025.1"
    app.kubernetes.io/managed-by: Helm
  name: hivemq-edge-config-my-platform
  namespace: default
data:
  config: |
    <mqtt-bridges>
    </mqtt-bridges>
    <protocol-adapters>
        <protocol-adapter>
            <protocolId>modbus</protocolId>
            <adapterId>test-modbus</adapterId>
            <config>
                <host>172.16.10.12</host>
                <port>502</port>
                <modbusToMqtt>
                    <maxPollingErrorsBeforeRemoval>-1</maxPollingErrorsBeforeRemoval>
                    <pollingIntervalMillis>5000</pollingIntervalMillis>
                    <publishChangedDataOnly>false</publishChangedDataOnly>
                </modbusToMqtt>
            </config>
            <northboundMappings>
                <northboundMapping>
                    <topic>topic</topic>
                    <maxQos>1</maxQos>
                    <includeTagNames>false</includeTagNames>
                    <includeTimestamp>true</includeTimestamp>
                    <messageHandlingOptions>MQTTMessagePerTag</messageHandlingOptions>
                    <mqttUserProperties>
                        <mqttUserProperty>
                            <name>coil</name>
                            <value>1</value>
                        </mqttUserProperty>
                    </mqttUserProperties>
                    <tagName>tag1</tagName>
                </northboundMapping>
                <northboundMapping>
                    <topic>topic</topic>
                    <maxQos>1</maxQos>
                    <includeTagNames>false</includeTagNames>
                    <includeTimestamp>true</includeTimestamp>
                    <messageHandlingOptions>MQTTMessagePerTag</messageHandlingOptions>
                    <mqttUserProperties>
                        <mqttUserProperty>
                            <name>coil</name>
                            <value>2</value>
                        </mqttUserProperty>
                    </mqttUserProperties>
                    <tagName>tag2</tagName>
                </northboundMapping>
            </northboundMappings>
            <tags>
                <tag>
                    <name>tag1</name>
                    <description>tag1</description>
                    <definition>
                        <dataType>BOOL</dataType>
                        <startIdx>0</startIdx>
                        <unitId>12</unitId>
                        <readType>COILS</readType>
                    </definition>
                </tag>
                <tag>
                    <name>tag2</name>
                    <description>tag2</description>
                    <definition>
                        <dataType>BOOL</dataType>
                        <startIdx>1</startIdx>
                        <unitId>12</unitId>
                        <readType>COILS</readType>
                    </definition>
                </tag>
            </tags>
        </protocol-adapter>
    </protocol-adapters>
