---
# Source: hivemq-edge/templates/configmap_configuration.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    helm.sh/chart: hivemq-edge-0.1.0
    app.kubernetes.io/name: "hivemq-edge"
    app.kubernetes.io/instance: "my-platform"
    app.kubernetes.io/version: "2025.1"
    app.kubernetes.io/managed-by: Helm
  name: hivemq-edge-config-my-platform
  namespace: default
data:
  config: |
    <mqtt-bridges>
    </mqtt-bridges>
    <protocol-adapters>
    </protocol-adapters>
