---
# Source: hivemq-platform-operator/templates/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivemq-my-operator
  labels:
    app.kubernetes.io/name: "hivemq-platform-operator"
    app.kubernetes.io/instance: "my-operator"
    app.kubernetes.io/version: "1.6.2"
spec:
  # The Operator cannot have more than one replica
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "hivemq-platform-operator"
      app.kubernetes.io/instance: "my-operator"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "hivemq-platform-operator"
        app.kubernetes.io/instance: "my-operator"
    spec:
      containers:
        - name: hivemq-platform-operator
          env:
            - name: JAVA_OPTS
              value: "-XX:+UnlockExperimentalVMOptions -XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HIVEMQ_PLATFORM_OPERATOR_RELEASE_NAME
              value: "my-operator"
            - name: HIVEMQ_PLATFORM_OPERATOR_CRD_APPLY
              value: "true"
            - name: HIVEMQ_PLATFORM_OPERATOR_CRD_WAIT_UNTIL_READY
              value: "true"
            - name: HIVEMQ_PLATFORM_OPERATOR_CRD_WAIT_UNTIL_READY_TIMEOUT
              value: "PT10S"
            - name: HIVEMQ_PLATFORM_OPERATOR_INIT_IMAGE
              value: "docker.io/hivemq/hivemq-platform-operator-init:1.6.2"
            - name: HIVEMQ_PLATFORM_OPERATOR_IMAGE_PULL_SECRET
              value: ""
            - name: HIVEMQ_PLATFORM_OPERATOR_LOG_LEVEL
              value: "INFO"
            - name: HIVEMQ_PLATFORM_OPERATOR_LOG_CONFIGURATION
              value: "false"
            - name: HIVEMQ_PLATFORM_OPERATOR_SERVICEACCOUNT_CREATE
              value: "true"
            - name: HIVEMQ_PLATFORM_OPERATOR_SERVICEACCOUNT_VALIDATE
              value: "true"
            - name: HIVEMQ_PLATFORM_OPERATOR_SERVICEACCOUNT_NAME
              value: ""
            - name: HIVEMQ_PLATFORM_OPERATOR_SERVICEACCOUNT_PERMISSIONS_CREATE
              value: "true"
            - name: HIVEMQ_PLATFORM_OPERATOR_SERVICEACCOUNT_PERMISSIONS_VALIDATE
              value: "true"
            - name: HIVEMQ_PLATFORM_OPERATOR_STATEFULSET_ROLLING_RESTART_ON_TEMPLATE_METADATA_CHANGE
              value: "false"
            - name: HIVEMQ_PLATFORM_OPERATOR_QUARKUS_LOG_LEVEL
              value: "INFO"
            - name: HIVEMQ_PLATFORM_OPERATOR_SDK_LOG_LEVEL
              value: "INFO"
            - name: HIVEMQ_PLATFORM_OPERATOR_NETWORK_LOG_LEVEL
              value: "WARN"
            - name: HIVEMQ_PLATFORM_OPERATOR_SKIP_HTTPS_CERTIFICATE_VALIDATION
              value: "false"
            - name: HIVEMQ_PLATFORM_OPERATOR_SKIP_HTTPS_HOSTNAME_VERIFICATION
              value: "false"
            - name: QUARKUS_HTTP_PORT
              value: "8080"
            - name: QUARKUS_HTTP_SSL_PORT
              value: "8443"
          image: "docker.io/hivemq/hivemq-platform-operator:1.6.2"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          ports:
            - name: http-my-operato
              containerPort: 8080
              protocol: TCP
            - name: https-my-operat
              containerPort: 8443
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 1Gi
      serviceAccountName: hivemq-platform-operator-my-operator
