apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hivemq-swarm-service-monitor
  labels:
    release: monitoring-stack # CUSTOMIZE: Helm release-name of the prometheus-stack
spec:
  selector:
    matchLabels:
      # agent and commander pods labels
      app.kubernetes.io/instance: swarm # CUSTOMIZE: Helm release-name of HiveMQ Swarm
      app.kubernetes.io/name: hivemq-swarm
  namespaceSelector:
    matchNames:
      - default # CUSTOMIZE: namespace of the Swarm deployment
  endpoints:
    # port name of the commander service to scrape
    - port: api
      interval: 15s
      scrapeTimeout: 10s
    # port name of the agent service to scrape
    - port: metrics
      interval: 15s
      scrapeTimeout: 10s
