{{- if .Values.operator.deployCr }}
kind: HiveMQCluster
apiVersion: hivemq.com/v1
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name | quote }}
    hivemq-cluster: {{ .Release.Name | quote }}
    {{- include "hivemq.labels" . | nindent 4 }}
  namespace: {{ template "hivemq.namespace" . }}
spec:
  nodeCount: {{ .Values.hivemq.nodeCount }}
  image: "{{- (splitn ":" 2 .Values.hivemq.image)._0 }}"
  hivemqVersion: "{{- (splitn ":" 2 .Values.hivemq.image)._1 }}"
  imagePullPolicy: {{ .Values.hivemq.imagePullPolicy }}
  {{- with .Values.global.rbac.imagePullSecrets }}
  imagePullSecrets:
  {{- range . }}
  - {{ .name | quote }}
  {{- end }}
  {{- end }}
  memory: {{ .Values.hivemq.memory }}
  memoryLimitRatio: {{ .Values.hivemq.memoryLimitRatio }}
  ephemeralStorage: {{ .Values.hivemq.ephemeralStorage }}
  ephemeralStorageLimitRatio: {{ .Values.hivemq.ephemeralStorageLimitRatio }}
  cpu: {{ .Values.hivemq.cpu | quote }}
  cpuLimitRatio: {{ .Values.hivemq.cpuLimitRatio }}
  restrictions: {{ toYaml .Values.hivemq.restrictions | nindent 4 }}
  {{- if .Values.hivemq.extensions }}
  extensions: {{ toYaml .Values.hivemq.extensions | nindent 4 }}
  {{- end }}
  security: {{ toYaml .Values.hivemq.security | nindent 4 }}
  logLevel: {{ .Values.hivemq.logLevel }}
  {{- if .Values.monitoring.enabled }}
  monitoring:
    enablePrometheus: true
  {{- end }}
  {{- if .Values.global.rbac.create }}
  serviceAccountName: "{{ template "hivemq.fullname" . }}-hivemq"
  {{- else }}
  serviceAccountName: "{{ .Values.hivemq.serviceAccountName }}"
  {{- end }}
  {{- if .Values.hivemq.secrets }}
  secrets: {{ toYaml .Values.hivemq.secrets | nindent 4 }}
  {{- end }}
  labels:
    {{- include "hivemq.labels" . | nindent 4 }}
  env: {{ toYaml .Values.hivemq.env | nindent 4 }}
  ports: {{ toYaml .Values.hivemq.ports | nindent 4 }}
  {{- if .Values.hivemq.configMaps }}
  configMaps: {{ toYaml .Values.hivemq.configMaps | nindent 4 }}
  {{- if .Values.hivemq.license }}
    - name: {{ include "hivemq.fullname" . }}-license
      path: /opt/hivemq/license
  {{- end }}
  {{- else if .Values.hivemq.license }}
  configMaps:
    - name: {{ include "hivemq.fullname" . }}-license
      path: /opt/hivemq/license
  {{- end }}
  mqtt: {{ toYaml .Values.hivemq.mqtt | nindent 4 }}
  clusterOverloadProtection: {{ .Values.hivemq.clusterOverloadProtection }}
  javaOptions: {{ .Values.hivemq.javaOptions }}
  clusterReplicaCount: {{ .Values.hivemq.clusterReplicaCount }}
  controllerTemplate: {{ .Values.hivemq.controllerTemplate }}
  affinity: |{{ .Values.hivemq.affinity | nindent 4 }}
  listenerConfiguration: |{{ .Values.hivemq.listenerConfiguration | nindent 4 }}
  restApiConfiguration: |{{ .Values.hivemq.restApiConfiguration | nindent 4 }}
  configOverride: |{{ .Values.hivemq.configOverride | nindent 4 }}
  initialization: {{ toYaml .Values.hivemq.initialization | nindent 4 }}
  sidecars: {{ toYaml .Values.hivemq.sidecars | nindent 4 }}
  initContainers: {{ toYaml .Values.hivemq.initContainers | nindent 4 }}
  {{- if .Values.hivemq.podSecurityContext }}
  podSecurityContext: {{ toYaml .Values.hivemq.podSecurityContext | nindent 4 }}
  {{- end }}
  {{- if .Values.hivemq.containerSecurityContext }}
  containerSecurityContext: {{ toYaml .Values.hivemq.containerSecurityContext | nindent 4 }}
  {{- end }}
  topologySpreadConstraints: {{ toYaml .Values.hivemq.topologySpreadConstraints | nindent 4 }}
  tolerations: {{ toYaml .Values.hivemq.tolerations | nindent 4 }}
  nodeSelector: {{ toYaml .Values.hivemq.nodeSelector | nindent 4 }}
  runtimeClassName: {{ toYaml .Values.hivemq.runtimeClassName | nindent 4 }}
  priorityClassName: {{ toYaml .Values.hivemq.priorityClassName | nindent 4 }}
  additionalVolumes: {{ toYaml .Values.hivemq.additionalVolumes | nindent 4 }}
  additionalVolumeMounts: {{ toYaml .Values.hivemq.additionalVolumeMounts | nindent 4 }}
  dnsSuffix: {{ toYaml .Values.hivemq.dnsSuffix | nindent 4 }}
  podAnnotations: {{ toYaml .Values.hivemq.podAnnotations | nindent 4 }}
  customProperties: {{ toYaml .Values.hivemq.customProperties | nindent 4 }}
  podLabels: {{ toYaml .Values.hivemq.podLabels | nindent 4 }}
  {{- if .Values.hivemq.operatorHints }}
  operatorHints: {{ toYaml .Values.hivemq.operatorHints | nindent 4 }}
  {{- end }}
  initBusyboxImage: {{ .Values.hivemq.initBusyboxImage }}
  initDnsWaitImage: {{ .Values.hivemq.initDnsWaitImage }}
  {{- if .Values.hivemq.volumeClaimTemplates }}
  volumeClaimTemplates: {{ toYaml .Values.hivemq.volumeClaimTemplates | nindent 4 }}
  {{- end }}

{{- end }}