apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ template "hivemq.fullname" . }}-operator"
  namespace: {{ template "hivemq.namespace" . }}
  labels:
    {{- include "hivemq.labels" . | nindent 4 }}