---
# Source: hivemq-operator/templates/hivemq-operator/operator-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "hivemq-operator"
  namespace: hivemq
  labels:
    app: hivemq-operator
