---
# Source: hivemq-operator/templates/hivemq-operator/operator-rolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "hivemq-operator-binding"
  labels:
    app: hivemq-operator
roleRef:
  name: "hivemq-operator"
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
  - name: "hivemq-operator"
    namespace: hivemq
    kind: ServiceAccount
