{{- if and .Values.global.rbac.create .Values.global.rbac.pspEnabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: "{{ template "hivemq.fullname" . }}"
  namespace: {{ template "hivemq.namespace" . }}
  labels:
    {{- include "hivemq.labels" . | nindent 4 }}
  {{- if .Values.global.rbac.pspAnnotations }}
  annotations:
  {{ toYaml .Values.global.rbac.pspAnnotations | indent 4 }}
  {{- end }}
spec:
  privileged: false
  # This is redundant with non-root + disallow privilege escalation,
  # but we can provide it for defense in depth.
  #requiredDropCapabilities:
  #  - ALL
  # Allow core volume types.
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    # Permits the container to run with root privileges as well.
    rule: 'MustRunAsNonRoot'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'MustRunAs'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
  {{- if .Values.global.rbac.allowedCapabilities }}
  allowedCapabilities:
  {{ toYaml .Values.global.rbac.allowedCapabilities | indent 4 }}
  {{- end }}
{{- end }}