global:
  rbac:
    pspEnabled: false

operator:
  image: hivemq/hivemq-operator:snapshot
  imagePullPolicy: Never
  logLevel: DEBUG
  admissionWebhooks:
    enabled: false

hivemq:
  image: hivemq/hivemq4-test:k8s-snapshot
  imagePullPolicy: Never
  initDnsWaitImage: hivemq/init-dns-wait:snapshot
  logLevel: DEBUG
  nodeCount: 1
  cpu: 1
  memory: 1Gi
  extensions:
    - name: hivemq-mqtt-message-log-extension
      extensionUri: https://github.com/hivemq/hivemq-mqtt-message-log-extension/releases/download/1.1.3/hivemq-mqtt-message-log-extension-1.1.3.zip
      enabled: true
      static: true