global:
  rbac:
    create: true
    pspEnabled: true
    pspAnnotations: { }
    allowedCapabilities: [ ]
    imagePullSecrets:
      - name: hmq-secret
  imagePullSecrets:
    - name: hmq-secret

hivemq:
  image: hivemq4-k8s-test:snapshot
  logLevel: DEBUG
  nodeCount: 1
  cpu: 1
  memory: 1Gi
  ports:
    - name: "mqtt"
      port: 1883
      expose: true
      patch:
        - '[{"op":"add","path":"/spec/type","value":"LoadBalancer"}]'
