# An example patch showing how to use initialization routines. While this example shows how to install an extension,
# you should use the 'extensions' field instead for this type of task.

apiVersion: hivemq.com/v1
kind: HiveMQCluster
spec:
  initialization:
    - name: init-kafka-plugin
      args:
        - |
          # Setup extension
          wget https://www.hivemq.com/releases/extensions/hivemq-kafka-extension-1.0.0.zip
          unzip hivemq-kafka-extension-1.0.0.zip -d /hivemq-data/extensions
          rm /hivemq-data/extensions/hivemq-kafka-extension/kafka-configuration.example.xml
          chmod -R 777 /hivemq-data/extensions/hivemq-kafka-extension