# An example patch showing how to manage extensions
# See https://github.com/hivemq/hivemq-mqtt-message-log-extension?tab=readme-ov-file#configuration on how to create the extension configuration

apiVersion: hivemq.com/v1
kind: HiveMQCluster
spec:
  extensions:
    - name: hivemq-mqtt-message-log-extension
      extensionUri: https://github.com/hivemq/hivemq-mqtt-message-log-extension/releases/download/1.1.3/hivemq-mqtt-message-log-extension-1.1.3.zip
      configMap: message-log-config
      enabled: true
