{
 "title": "HiveMQ Platform (Prometheus)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(com_hivemq_cluster_nodes_count, namespace)"
    }
   },
   { "name": "intervalSeconds", "label": "Interval Seconds", "query": "5,10,30,60,120" },
   { "name": "Route", "label": "Route", "query": "total" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU %",
   "type": "timeseries",
   "description": "Percentage of total CPU utilisation.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "com_hivemq_system_os_global_cpu_total_total{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} cpu.total"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "description": "- *total*: The amount of actual physical memory.\n- *available*: The amount of physical memory currently available.",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "com_hivemq_system_os_global_memory_total{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} memory.total"
    },
    {
     "expr": "com_hivemq_system_os_global_memory_available{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} memory.available"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "description": "- *used*: The amount of used memory.\n- *max*: The maximum amount of memory that can be used for memory management.\n- *init*: The amount of memory that the JVM initially requests from the operating system for memory management.",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "com_hivemq_jvm_memory_heap_max{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} heap.max"
    },
    {
     "expr": "com_hivemq_jvm_memory_heap_init{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} heap.init"
    },
    {
     "expr": "com_hivemq_jvm_memory_heap_used{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} heap.used"
    }
   ]
  },
  {
   "title": "Current MQTT Connections",
   "type": "timeseries",
   "description": "The number of active MQTT connections.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "com_hivemq_networking_connections_current{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} connections"
    }
   ]
  },
  {
   "title": "Cluster Nodes",
   "type": "timeseries",
   "description": "The number of nodes in the cluster.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "com_hivemq_cluster_nodes_count{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} nodes"
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "incoming Bytes/s",
   "type": "timeseries",
   "description": "The amount of data received for each network interface. Measured in bytes per second.",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"com_hivemq_system_os_network_interface_.+_bytes_received\", namespace=~\"$namespace\"}, \"interface\", \"$1\", \"__name__\", \"com_hivemq_system_os_network_interface_(.+)_bytes_received\")[5m:${intervalSeconds}s])",
     "legendFormat": "{{instance}} {{interface}} bytes.incoming"
    }
   ]
  },
  {
   "title": "outgoing Bytes/s",
   "type": "timeseries",
   "description": "The amount of data sent for each network interface. Measured in bytes per second.",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"com_hivemq_system_os_network_interface_.+_bytes_sent\", namespace=~\"$namespace\"}, \"interface\", \"$1\", \"__name__\", \"com_hivemq_system_os_network_interface_(.+)_bytes_sent\")[5m:${intervalSeconds}s])",
     "legendFormat": "{{instance}} {{interface}} bytes.outgoing"
    }
   ]
  },
  {
   "title": "Disk Bytes Read/s",
   "type": "timeseries",
   "description": "The amount of data read for each disk. Measured in bytes per second.",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"com_hivemq_system_os_disks_(.*)_read_bytes\", namespace=~\"$namespace\"}, \"disk\", \"$1\", \"__name__\", \"com_hivemq_system_os_disks_(.*)_read_bytes\")[5m:${intervalSeconds}s])",
     "legendFormat": "{{instance}} {{disk}} bytes.read"
    }
   ]
  },
  {
   "title": "Disk Bytes Written/s",
   "type": "timeseries",
   "description": "The amount of data written for each disk. Measured in bytes per second.",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"com_hivemq_system_os_disks_.+_write_bytes\", namespace=~\"$namespace\"}, \"disk\", \"$1\", \"__name__\", \"com_hivemq_system_os_disks_(.+)_write_bytes\")[5m:${intervalSeconds}s])",
     "legendFormat": "{{instance}} {{disk}} bytes.written"
    }
   ]
  },
  {
   "title": "Single Writer Tasks/s",
   "type": "timeseries",
   "description": "The number of disk I/O tasks in the queue for each persistence executor.",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"com_hivemq_persistence_executor_(.*)_tasks\",  __name__!=\"(.*)total(.*)\", namespace=~\"$namespace\"}, \"executor\", \"$1\", \"__name__\", \"com_hivemq_persistence_executor_(.*)_tasks\")[5m:${intervalSeconds}s])",
     "legendFormat": "{{executor}} tasks.count"
    }
   ]
  },
  { "title": "MQTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Current MQTT Connections",
   "type": "timeseries",
   "description": "The number of active MQTT connections.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "com_hivemq_networking_connections_current{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} connections"
    }
   ]
  },
  {
   "title": "Current MQTT Sessions",
   "type": "timeseries",
   "description": "The number of stored sessions. These sessions include all sessions, including online and offline clients.",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "com_hivemq_sessions_overall_current{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} sessions"
    }
   ]
  },
  {
   "title": "Current Subscriptions",
   "type": "timeseries",
   "description": "The number of subscriptions on the broker.",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 17 },
   "targets": [
    {
     "expr": "com_hivemq_subscriptions_overall_current{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} subscriptions"
    }
   ]
  },
  {
   "title": "Queued Messages",
   "type": "timeseries",
   "description": "The number of queued messages.",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "com_hivemq_messages_queued_count{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} queued"
    }
   ]
  },
  {
   "title": "Retained Messages",
   "type": "timeseries",
   "description": "The number of retained messages.",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 17 },
   "targets": [
    {
     "expr": "com_hivemq_messages_retained_current{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} retained"
    }
   ]
  },
  {
   "title": "Dropped Messages/s",
   "type": "timeseries",
   "description": "The number of messages dropped for grouped by reason, per second.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"com_hivemq_messages_dropped_(.+)_count\", __name__!~\"(.*)total(.*)\", __name__!~\"(.*)dropped_topic(.*)\", namespace=~\"$namespace\"}, \"reason\", \"$1\", \"__name__\", \"com_hivemq_messages_dropped_(.+)_count\")[5m:${intervalSeconds}s])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "MQTT PUBLISH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "incoming PUBLISH/s",
   "type": "timeseries",
   "description": "The number of incoming PUBLISH messages per second.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_incoming_publish_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{job}} incoming.publish"
    }
   ]
  },
  {
   "title": "outgoing PUBLISH/s",
   "type": "timeseries",
   "description": "The number of outgoing PUBLISH messages per second.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_outgoing_publish_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{instance}} outgoing.publish"
    }
   ]
  },
  {
   "title": "incoming PUBACK/s",
   "type": "timeseries",
   "description": "The number of incoming PUBACK messages per second.",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_incoming_puback_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{instance}} incoming.puback"
    }
   ]
  },
  {
   "title": "outgoing PUBACK/s",
   "type": "timeseries",
   "description": "The number of outgoing PUBACK messages per second.",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 25 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_outgoing_puback_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{instance}} outgoing.publish"
    }
   ]
  },
  {
   "title": "incoming PUBREC/s",
   "type": "timeseries",
   "description": "The number of incoming PUBREC messages per second.",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 25 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_incoming_pubrec_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{instance}} incoming.pubrec"
    }
   ]
  },
  {
   "title": "outgoing PUBREC/s",
   "type": "timeseries",
   "description": "The number of outgoing PUBREC messages per second.",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 25 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_outgoing_pubrec_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{instance}} outgoing.publish"
    }
   ]
  },
  {
   "title": "incoming PUBREL/s",
   "type": "timeseries",
   "description": "The number of incoming PUBREL messages per second.",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_incoming_pubrel_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{instance}} incoming.pubrel"
    }
   ]
  },
  {
   "title": "outgoing PUBREL/s",
   "type": "timeseries",
   "description": "The number of outgoing PUBREL messages per second.",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 32 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_outgoing_pubrel_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{instance}} outgoing.publish"
    }
   ]
  },
  {
   "title": "incoming PUBCOMP/s",
   "type": "timeseries",
   "description": "The number of incoming PUBCOMP messages per second.",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 32 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_incoming_pubcomp_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{instance}} incoming.pubcomp"
    }
   ]
  },
  {
   "title": "outgoing PUBCOMP/s",
   "type": "timeseries",
   "description": "The number of outgoing PUBCOMP messages per second.",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 32 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_outgoing_pubcomp_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{instance}} outgoing.publish"
    }
   ]
  },
  { "title": "MQTT Control Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "incoming CONNECT/s",
   "type": "timeseries",
   "description": "The number of incoming CONNECT messages per second.",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_incoming_connect_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{instance}} incoming.connect"
    }
   ]
  },
  {
   "title": "outgoing CONACK/s",
   "type": "timeseries",
   "description": "The number of outgoing CONACK messages per second.",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 40 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_outgoing_connack_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{instance}} incoming.connect"
    }
   ]
  },
  {
   "title": "incoming SUBSCRIBE/s",
   "type": "timeseries",
   "description": "The number of incoming SUBSCRIBE messages per second.",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 40 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_incoming_subscribe_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{instance}} incoming.subscribe"
    }
   ]
  },
  {
   "title": "outgoing SUBACK/s",
   "type": "timeseries",
   "description": "The number of outgoing SUBACK messages per second.",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 40 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_outgoing_suback_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{instance}} incoming.subscribe"
    }
   ]
  },
  {
   "title": "incoming UNSUBSCRIBE/s",
   "type": "timeseries",
   "description": "The number of incoming UNSUBSCRIBE messages per second.",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_incoming_unsubscribe_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{instance}} incoming.unsubscribe"
    }
   ]
  },
  {
   "title": "outgoing UNSUBACK/s",
   "type": "timeseries",
   "description": "The number of outgoing UNSUBACK messages per second.",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 40 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_outgoing_unsuback_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{instance}} incoming.unsubscribe"
    }
   ]
  },
  {
   "title": "incoming PINGRESP/s",
   "type": "timeseries",
   "description": "The number of incoming PINGRESP messages per second.",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 40 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_incoming_pingreq_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{instance}} incoming.pingreq"
    }
   ]
  },
  {
   "title": "outgoing PINGRESP/s",
   "type": "timeseries",
   "description": "The number of outgoing PINGRESP messages per second.",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 40 },
   "targets": [
    {
     "expr": "rate(com_hivemq_messages_outgoing_pingresp_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{instance}} outgoing.pingresp"
    }
   ]
  },
  {
   "title": "Overload Protection & Throttling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }
  },
  {
   "title": "Overload Protection Level",
   "type": "timeseries",
   "description": "The level of overload protection, from Lowest (1) to CRITICAL (10)",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "com_hivemq_overload_protection_level{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overload Protection Backpressure Active",
   "type": "timeseries",
   "description": "The number of clients for which backpressure is applied by overload protection.",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 48 },
   "targets": [
    {
     "expr": "com_hivemq_overload_protection_clients_backpressure_active{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Currently Throttled Connections",
   "type": "timeseries",
   "description": "The number of client connections whose reads are currently suspended because the configured incoming-bandwidth-throttling limit is being enforced. A value greater than 0 means incoming bandwidth throttling is currently active.",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 48 },
   "targets": [
    {
     "expr": "com_hivemq_networking_incoming_bandwidth_throttling_connections_current{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throttle Events/s",
   "type": "timeseries",
   "description": "Counts each time a client connection's reads are suspended because the configured incoming-bandwidth-throttling limit is being enforced",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 48 },
   "targets": [
    {
     "expr": "rate(com_hivemq_networking_incoming_bandwidth_throttling_connections_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{job}} throttle-events"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Heap",
   "type": "timeseries",
   "description": "- *used*: The amount of used memory.\n- *max*: The maximum amount of memory that can be used for memory management.\n- *init*: The amount of memory that the JVM initially requests from the operating system for memory management.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "com_hivemq_jvm_memory_heap_max{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} heap.max"
    },
    {
     "expr": "com_hivemq_jvm_memory_heap_init{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} heap.init"
    },
    {
     "expr": "com_hivemq_jvm_memory_heap_used{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} heap.used"
    }
   ]
  },
  {
   "title": "GC/s",
   "type": "timeseries",
   "description": "- *old-gen*: The number of old generation garbage collections per second.\n- *young-gen*: The number of young generation garbage collections per second.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 56 },
   "targets": [
    {
     "expr": "rate(com_hivemq_jvm_garbage_collector_G1_Old_Generation_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{job}} old.gen.count"
    },
    {
     "expr": "rate(com_hivemq_jvm_garbage_collector_G1_Young_Generation_count{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{job}} young.gen.count"
    }
   ]
  },
  {
   "title": "GC times",
   "type": "timeseries",
   "description": "- *old-gen*: The approximate accumulated elapsed time for old generation garbage collections.\n- *young-gen*: The approximate accumulated elapsed time for young generation garbage collections.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(com_hivemq_jvm_garbage_collector_G1_Old_Generation_time{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{job}} old.gen.time"
    },
    {
     "expr": "rate(com_hivemq_jvm_garbage_collector_G1_Young_Generation_time{namespace=~\"$namespace\"}[${intervalSeconds}s])",
     "legendFormat": "{{job}} young.gen.time"
    }
   ]
  },
  {
   "title": "HiveMQ Enterprise Extension for Amazon Kinesis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "MQTT to Amazon Kinesis success/s",
     "type": "timeseries",
     "description": "The number of MQTT to Amazon Kinesis messages that the extension successfully forwards for each mqtt-to-kinesis-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_(.+)_success_count\", __name__!=\"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_total_success_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_(.+)_success_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to Amazon Kinesis failure/s",
     "type": "timeseries",
     "description": "The number of MQTT to Amazon Kinesis messages that the extension cannot successfully forward for each mqtt-to-kinesis-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 64 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_(.+)_failed_count\", __name__!=\"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_total_failed_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_(.+)_failed_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to Amazon Kinesis sent/s",
     "type": "timeseries",
     "description": "The number of MQTT to Amazon Kinesis messages the extension sends for each mqtt-to-kinesis-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 64 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_(.+)_sent_count\", __name__!=\"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_total_sent_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_(.+)_sent_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to Amazon Kinesis resent/s",
     "type": "timeseries",
     "description": "The number of MQTT to Amazon Kinesis messages the extension resends for each mqtt-to-kinesis-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 64 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_(.+)_resent_count\", __name__!=\"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_total_resent_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_(.+)_resent_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to Amazon Kinesis ignored/s",
     "type": "timeseries",
     "description": "The number of MQTT to Amazon Kinesis messages the extension ignores for each mqtt-to-kinesis-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_(.+)_ignored_count\", __name__!=\"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_total_ignored_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_(.+)_ignored_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to Amazon Kinesis dropped/s",
     "type": "timeseries",
     "description": "The number of MQTT to Amazon Kinesis messages the extension drops for each mqtt-to-kinesis-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 71 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_(.+)_dropped_count\", __name__!=\"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_total_dropped_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_amazon_kinesis_mqtt_to_kinesis_(.+)_dropped_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "Amazon Kinesis to MQTT success/s",
     "type": "timeseries",
     "description": "The number of Amazon Kinesis to MQTT messages that the extension successfully forwards for each kinesis-to-mqtt-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 71 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_(.+)_success_count\", __name__!=\"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_total_success_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_(.+)_success_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "Amazon Kinesis to MQTT failure/s",
     "type": "timeseries",
     "description": "The number of Amazon Kinesis to MQTT messages that the extension cannot successfully forward for each kinesis-to-mqtt-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 71 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_(.+)_failed_count\", __name__!=\"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_total_failed_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_(.+)_failed_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "Amazon Kinesis to MQTT sent/s",
     "type": "timeseries",
     "description": "The number of Amazon Kinesis to MQTT messages that the extension send for each kinesis-to-mqttroute, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_(.+)_sent_count\", __name__!=\"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_total_sent_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_(.+)_sent_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "Amazon Kinesis to MQTT ignored/s",
     "type": "timeseries",
     "description": "The number of Amazon Kinesis to MQTT messages that the extension ignores for each kinesis-to-mqtt-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 78 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_(.+)_ignored_count\", __name__!=\"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_total_ignored_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_(.+)_ignored_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "Amazon Kinesis to MQTT dropped/s",
     "type": "timeseries",
     "description": "The number of Amazon Kinesis to MQTT messages that the extension drops for each kinesis-to-mqtt-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 78 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_(.+)_dropped_count\", __name__!=\"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_total_dropped_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_(.+)_dropped_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "Amazon Kinesis to MQTT rate-limit-exceeded/s",
     "type": "timeseries",
     "description": "The number of Amazon Kinesis to MQTT messages that exceed the configured rate-limit for each kinesis-to-mqtt-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 78 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_(.+)_rate_limit_exceeded_count\", __name__!=\"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_total_rate_limit_exceeded_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_(.+)_rate_limit_exceeded_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "Amazon Kinesis to MQTT received/s",
     "type": "timeseries",
     "description": "The number of Amazon Kinesis to MQTT messages that the extension receives for each kinesis-to-mqtt-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_(.+)_received_count\", __name__!=\"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_total_received_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_amazon_kinesis_kinesis_to_mqtt_(.+)_received_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HiveMQ Enterprise Bridge Extension",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "outgoing PUBLISH/s",
     "type": "timeseries",
     "description": "The rate of PUBLISH messages the extension forwards to remote brokers for each bridge, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_bridge_extension_(.+)_publish_meter_total\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_bridge_extension_(.+)_publish_meter_total\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "incoming PUBLISH failed/s",
     "type": "timeseries",
     "description": "The rate of PUBLISH messages the extension forwards to remote brokers for each bridge, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 65 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_bridge_extension_(.+)_publish_failed_meter_total\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_bridge_extension_(.+)_publish_failed_meter_total\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "incoming PUBLISH/s",
     "type": "timeseries",
     "description": "The rate at which the extension receives SUB mode messages from the remote broker for each bridge, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 65 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_bridge_extension_(.+)_subscribed_message_meter_total\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_bridge_extension_(.+)_subscribed_message_meter_total\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "incoming PUBLISH failed/s",
     "type": "timeseries",
     "description": "The rate at which the extension is unable to receive SUB mode messages from the remote broker for each bridge, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 65 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_bridge_extension_(.+)_subscribed_message_failed_meter_total\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_bridge_extension_(.+)_subscribed_message_failed_meter_total\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HiveMQ Enterprise Data Lake Extension",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "MQTT to S3 success/s",
     "type": "timeseries",
     "description": "The number of MQTT to S3 messages that the extension successfully forwards for each mqtt-to-s3-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_data_lake_mqtt_to_s3_(.+)_success_count\", __name__!=\"com_hivemq_extensions_data_lake_mqtt_to_s3_total_success_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_data_lake_mqtt_to_s3_(.+)_success_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to S3 failed/s",
     "type": "timeseries",
     "description": "The number of MQTT to S3 messages that the extension cannot successfully forward for each mqtt-to-s3-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 66 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_data_lake_mqtt_to_s3_(.+)_failed_count\", __name__!=\"com_hivemq_extensions_data_lake_mqtt_to_s3_total_failed_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_data_lake_mqtt_to_s3_(.+)_failed_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HiveMQ Enterprise Extension for Google Cloud Pub/Sub",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "MQTT to PubSub success/s",
     "type": "timeseries",
     "description": "The number of MQTT to PubSub messages that the extension successfully forwards for each mqtt-to-pubsub-mapping/mqtt-to-pubsub-transformer, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_google_cloud_pubsub_mqtt_to_pubsub_(transformer|mapping)_(.+)_sent_count\", __name__!~\".*total.*\", namespace=~\"$namespace\"}, \"route\", \"$2\", \"__name__\", \"com_hivemq_extensions_google_cloud_pubsub_mqtt_to_pubsub_(transformer|mapping)_(.+)_sent_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to PubSub failed/s",
     "type": "timeseries",
     "description": "The number of MQTT to PubSub messages that the extension cannot successfully forward for each mqtt-to-pubsub-mapping/mqtt-to-pubsub-transformer, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 67 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_google_cloud_pubsub_mqtt_to_pubsub_(transformer|mapping)_(.+)_failed_count\", __name__!~\".*total.*\", namespace=~\"$namespace\"}, \"route\", \"$2\", \"__name__\", \"com_hivemq_extensions_google_cloud_pubsub_mqtt_to_pubsub_(transformer|mapping)_(.+)_failed_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to PubSub sent/s",
     "type": "timeseries",
     "description": "The number of MQTT to PubSub messages the extension sends for each mqtt-to-pubsub-mapping/mqtt-to-pubsub-transformer, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_google_cloud_pubsub_mqtt_to_pubsub_(transformer|mapping)_(.+)_sent_count\", __name__!~\".*total.*\", namespace=~\"$namespace\"}, \"route\", \"$2\", \"__name__\", \"com_hivemq_extensions_google_cloud_pubsub_mqtt_to_pubsub_(transformer|mapping)_(.+)_sent_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to PubSub resent/s",
     "type": "timeseries",
     "description": "The number of MQTT to PubSub messages the extension resends for each mqtt-to-pubsub-mapping/mqtt-to-pubsub-transformer, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 67 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_google_cloud_pubsub_mqtt_to_pubsub_(transformer|mapping)_(.+)_resent_count\", __name__!~\".*total.*\", namespace=~\"$namespace\"}, \"route\", \"$2\", \"__name__\", \"com_hivemq_extensions_google_cloud_pubsub_mqtt_to_pubsub_(transformer|mapping)_(.+)_resent_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to PubSub ignored/s",
     "type": "timeseries",
     "description": "The number of MQTT to PubSub messages the extension ignores for each mqtt-to-pubsub-mapping/mqtt-to-pubsub-transformer, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_google_cloud_pubsub_mqtt_to_pubsub_(transformer|mapping)_(.+)_ignored_count\", __name__!~\".*total.*\", namespace=~\"$namespace\"}, \"route\", \"$2\", \"__name__\", \"com_hivemq_extensions_google_cloud_pubsub_mqtt_to_pubsub_(transformer|mapping)_(.+)_ignored_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to PubSub dropped/s",
     "type": "timeseries",
     "description": "The number of MQTT to PubSub messages the extension drops for each mqtt-to-pubsub-mapping/mqtt-to-pubsub-transformer, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 74 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_google_cloud_pubsub_mqtt_to_pubsub_(transformer|mapping)_(.+)_dropped_count\", __name__!~\".*total.*\", namespace=~\"$namespace\"}, \"route\", \"$2\", \"__name__\", \"com_hivemq_extensions_google_cloud_pubsub_mqtt_to_pubsub_(transformer|mapping)_(.+)_dropped_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "PubSub to MQTT success/s",
     "type": "timeseries",
     "description": "The number of PubSub to MQTT messages that the extension successfully forwards for each pubsub-to-mqtt-mapping/pubsub-to-mqtt-transformer, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 74 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_google_cloud_pubsub_pubsub_to_mqtt_(transformer|mapping)_(.+)_success_count\", __name__!~\".*total.*\", namespace=~\"$namespace\"}, \"route\", \"$2\", \"__name__\", \"com_hivemq_extensions_google_cloud_pubsub_pubsub_to_mqtt_(transformer|mapping)_(.+)_success_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "PubSub to MQTT failed/s",
     "type": "timeseries",
     "description": "The number of PubSub to MQTT messages that the extension cannot successfully forward for each pubsub-to-mqtt-mapping/pubsub-to-mqtt-transformer, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 74 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_google_cloud_pubsub_pubsub_to_mqtt_(transformer|mapping)_(.+)_failed_count\", __name__!~\".*total.*\", namespace=~\"$namespace\"}, \"route\", \"$2\", \"__name__\", \"com_hivemq_extensions_google_cloud_pubsub_pubsub_to_mqtt_(transformer|mapping)_(.+)_failed_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "PubSub to MQTT received/s",
     "type": "timeseries",
     "description": "The number of PubSub to MQTT messages that the extension receives for each pubsub-to-mqtt-mapping/pubsub-to-mqtt-transformer, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_google_cloud_pubsub_pubsub_to_mqtt_(transformer|mapping)_(.+)_received_count\", __name__!~\".*total.*\", namespace=~\"$namespace\"}, \"route\", \"$2\", \"__name__\", \"com_hivemq_extensions_google_cloud_pubsub_pubsub_to_mqtt_(transformer|mapping)_(.+)_received_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "PubSub to MQTT PUBLISH/s",
     "type": "timeseries",
     "description": "The number of PubSub to MQTT messages that the extension publishes for each pubsub-to-mqtt-mapping/pubsub-to-mqtt-transformer, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 81 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_google_cloud_pubsub_pubsub_to_mqtt_(transformer|mapping)_(.+)_sent_count\", __name__!~\".*total.*\", namespace=~\"$namespace\"}, \"route\", \"$2\", \"__name__\", \"com_hivemq_extensions_google_cloud_pubsub_pubsub_to_mqtt_(transformer|mapping)_(.+)_sent_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "PubSub to MQTT resent/s",
     "type": "timeseries",
     "description": "The number of PubSub to MQTT messages that the extension resends for each pubsub-to-mqtt-mapping/pubsub-to-mqtt-transformer, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 81 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_google_cloud_pubsub_pubsub_to_mqtt_(transformer|mapping)_(.+)_resent_count\", __name__!~\".*total.*\", namespace=~\"$namespace\"}, \"route\", \"$2\", \"__name__\", \"com_hivemq_extensions_google_cloud_pubsub_pubsub_to_mqtt_(transformer|mapping)_(.+)_resent_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "PubSub to MQTT ignored/s",
     "type": "timeseries",
     "description": "The number of PubSub to MQTT messages that the extension ignores for each pubsub-to-mqtt-mapping/pubsub-to-mqtt-transformer, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 81 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_google_cloud_pubsub_pubsub_to_mqtt_(transformer|mapping)_(.+)_ignored_count\", __name__!~\".*total.*\", namespace=~\"$namespace\"}, \"route\", \"$2\", \"__name__\", \"com_hivemq_extensions_google_cloud_pubsub_pubsub_to_mqtt_(transformer|mapping)_(.+)_ignored_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "PubSub to MQTT dropped/s",
     "type": "timeseries",
     "description": "The number of PubSub to MQTT messages that the extension drops for each pubsub-to-mqtt-mapping/pubsub-to-mqtt-transformer, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 88 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_google_cloud_pubsub_pubsub_to_mqtt_(transformer|mapping)_(.+)_dropped_count\", __name__!~\".*total.*\", namespace=~\"$namespace\"}, \"route\", \"$2\", \"__name__\", \"com_hivemq_extensions_google_cloud_pubsub_pubsub_to_mqtt_(transformer|mapping)_(.+)_dropped_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "PubSub to MQTT rate limit exceeded/s",
     "type": "timeseries",
     "description": "The number of PubSub to MQTT messages that exceed the configured rate limit for each pubsub-to-mqtt-mapping/pubsub-to-mqtt-transformer, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 88 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_google_cloud_pubsub_pubsub_to_mqtt_(transformer|mapping)_(.+)_rate_limit_exceeded_count\", __name__!~\".*total.*\", namespace=~\"$namespace\"}, \"route\", \"$2\", \"__name__\", \"com_hivemq_extensions_google_cloud_pubsub_pubsub_to_mqtt_(transformer|mapping)_(.+)_rate_limit_exceeded_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HiveMQ Enterprise Extension for Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "MQTT to Kafka success/s",
     "type": "timeseries",
     "description": "The number of MQTT to Kafka messages the extension successfully forwards for each mqtt-to-kafka-mapping/mqtt-to-kafka-transformer, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"kafka_extension_topic_mapping_(.+)_success_count\", namespace=~\"$namespace\"}, \"mapping\", \"$1\", \"__name__\", \"kafka_extension_topic_mapping_(.+)_success_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{mapping}} success.count"
      },
      {
       "expr": "rate(label_replace({__name__=~\"kafka_extension_transformer_(.+)_success_count\", namespace=~\"$namespace\"}, \"transformer\", \"$1\", \"__name__\", \"kafka_extension_transformer_(.+)_success_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{transformer}} success.count"
      }
     ]
    },
    {
     "title": "Kafka to MQTT polled record/s",
     "type": "timeseries",
     "description": "The number of Kafka records the extension polls for each kafka-to-mqtt-mapping/kafka-to-mqtt-transformer, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 68 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"kafka_extension_kafka_to_mqtt_mapping_(.+)_polled_record_count\", namespace=~\"$namespace\"}, \"mapping\", \"$1\", \"__name__\", \"kafka_extension_kafka_to_mqtt_mapping_(.+)_polled_record_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{mapping}} polled-record"
      },
      {
       "expr": "rate(label_replace({__name__=~\"kafka_extension_kafka_to_mqtt_transformer_(.+)_polled_record_count\", namespace=~\"$namespace\"}, \"transformer\", \"$1\", \"__name__\", \"kafka_extension_kafka_to_mqtt_transformer_(.+)_polled_record_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{transformer}} polled-record"
      }
     ]
    },
    {
     "title": "Kafka to MQTT PUBLISH/s",
     "type": "timeseries",
     "description": "The number of messages the extension publishes for each kafka-to-mqtt-mapping/kafka-to-mqtt-transformer, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 68 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"kafka_extension_kafka_to_mqtt_mapping_(.+)_send_publishes_count\", namespace=~\"$namespace\"}, \"mapping\", \"$1\", \"__name__\", \"kafka_extension_kafka_to_mqtt_mapping_(.+)_send_publishes_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{mapping}} publish.sent"
      },
      {
       "expr": "rate(label_replace({__name__=~\"kafka_extension_kafka_to_mqtt_transformer_(.+)_send_publishes_count\", namespace=~\"$namespace\"}, \"transformer\", \"$1\", \"__name__\", \"kafka_extension_kafka_to_mqtt_transformer_(.+)_send_publishes_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{transformer}} publish.sent"
      }
     ]
    }
   ]
  },
  {
   "title": "HiveMQ Enterprise Extension for MongoDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "MQTT to MongoDB success/s",
     "type": "timeseries",
     "description": "The number of MQTT to MongoDB messages that the extension successfully forwards for each mqtt-to-mongodb-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_mongodb_mqtt_to_mongodb_(.+)_success_count\", __name__!=\"com_hivemq_extensions_mongodb_mqtt_to_mongodb_total_success_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_mongodb_mqtt_to_mongodb_(.+)_success_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to MongoDB failed/s",
     "type": "timeseries",
     "description": "The number of MQTT to MongoDB messages that the extension cannot successfully forward for each mqtt-to-mongodb-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 69 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_mongodb_mqtt_to_mongodb_(.+)_failed_count\", __name__!=\"com_hivemq_extensions_mongodb_mqtt_to_mongodb_total_failed_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_mongodb_mqtt_to_mongodb_(.+)_failed_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to MongoDB consumer-incoming/s",
     "type": "timeseries",
     "description": "The number of MQTT to MongoDB messages that the extension's MessageConsumer receives.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 69 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_mongodb_mqtt_to_mongodb_(.+)_consumer_incoming_count\", __name__!=\"com_hivemq_extensions_mongodb_mqtt_to_mongodb_total_consumer_incoming_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_mongodb_mqtt_to_mongodb_(.+)_consumer_incoming_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{job}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to MongoDB in progress",
     "type": "timeseries",
     "description": "The current number of MQTT to MongoDB messages that are in the progress of being forwarded to PostgreSQL.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 69 },
     "targets": [
      {
       "expr": "label_replace({__name__=~\"com_hivemq_extensions_mongodb_mqtt_to_mongodb_(.+)_in_progress_count_current\", __name__!=\"com_hivemq_extensions_mongodb_mqtt_to_mongodb_total_in_progress_count_current\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_mongodb_mqtt_to_mongodb_(.+)_in_progress_count_current\")",
       "legendFormat": "{{job}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to MongoDB ${Route} Latency",
     "type": "timeseries",
     "description": "A histogram of the latency of all MQTT to MongoDB messages.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "com_hivemq_extensions_mongodb_mqtt_to_mongodb_${Route}_latency{namespace=~\"$namespace\"} * 1000",
       "legendFormat": "{{job}} {{quantile}} "
      }
     ]
    }
   ]
  },
  {
   "title": "HiveMQ Enterprise Extension for MySQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "MQTT to MySQL success/s",
     "type": "timeseries",
     "description": "The number of MQTT to MySQL messages that the extension successfully forwards for each mqtt-to-mysql-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_mysql_mqtt_to_mysql_(.+)_success_count\", __name__!=\"com_hivemq_extensions_mysql_mqtt_to_mysql_total_success_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_mysql_mqtt_to_mysql_(.+)_success_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to MySQL failed/s",
     "type": "timeseries",
     "description": "The number of MQTT to MySQL messages that the extension cannot successfully forward for each mqtt-to-mysql-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 70 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_mysql_mqtt_to_mysql_(.+)_failed_count\", __name__!=\"com_hivemq_extensions_mysql_mqtt_to_mysql_total_failed_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_mysql_mqtt_to_mysql_(.+)_failed_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to MySQL consumer-incoming/s",
     "type": "timeseries",
     "description": "The number of MQTT to MySQL messages that the extension's MessageConsumer receives.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 70 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_mysql_mqtt_to_mysql_(.+)_consumer_incoming_count\", __name__!=\"com_hivemq_extensions_mysql_mqtt_to_mysql_total_consumer_incoming_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_mysql_mqtt_to_mysql_(.+)_consumer_incoming_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{job}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to MySQL in progress",
     "type": "timeseries",
     "description": "The current number of MQTT to MySQL messages that are in the progress of being forwarded to PostgreSQL.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 70 },
     "targets": [
      {
       "expr": "label_replace({__name__=~\"com_hivemq_extensions_mysql_mqtt_to_mysql_(.+)_in_progress_count_current\", __name__!=\"com_hivemq_extensions_mysql_mqtt_to_mysql_total_in_progress_count_current\", __name__!~\"com_hivemq_extensions_mysql_mqtt_to_mysql_(.+)batches_in_progress_count_current\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_mysql_mqtt_to_mysql_(.+)_in_progress_count_current\")",
       "legendFormat": "{{job}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to MySQL batches in progress",
     "type": "timeseries",
     "description": "The current number of MQTT to MySQL batches that are in the progress of being forwarded to MySQL.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": "label_replace({__name__=~\"com_hivemq_extensions_mysql_mqtt_to_mysql_(.+)_batches_in_progress_count_current\", __name__!=\"com_hivemq_extensions_mysql_mqtt_to_mysql_total_batches_in_progress_count_current\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_mysql_mqtt_to_mysql_(.+)_batches_in_progress_count_current\")",
       "legendFormat": "{{job}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to MySQL ${Route} Latency",
     "type": "timeseries",
     "description": "A histogram of the latency of all MQTT to MySQL messages.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "com_hivemq_extensions_mysql_mqtt_to_mysql_${Route}_latency{namespace=~\"$namespace\"} * 1000",
       "legendFormat": "{{job}} {{quantile}} "
      }
     ]
    }
   ]
  },
  {
   "title": "HiveMQ Enterprise Extension for PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "MQTT to PostgreSQL success/s",
     "type": "timeseries",
     "description": "The number of MQTT to PostgreSQL messages that the extension successfully forwards for each mqtt-to-postgresql-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_postgresql_mqtt_to_postgresql_(.+)_success_count\", __name__!=\"com_hivemq_extensions_postgresql_mqtt_to_postgresql_total_success_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_postgresql_mqtt_to_postgresql_(.+)_success_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{job}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to PostgreSQL failed/s",
     "type": "timeseries",
     "description": "The number of MQTT to PostgreSQL messages that the extension cannot successfully forward for each mqtt-to-postgresql-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 71 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_postgresql_mqtt_to_postgresql_(.+)_failed_count\", __name__!=\"com_hivemq_extensions_postgresql_mqtt_to_postgresql_total_failed_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_postgresql_mqtt_to_postgresql_(.+)_failed_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{job}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to PostgreSQL consumer-incoming/s",
     "type": "timeseries",
     "description": "The number of MQTT to PostgreSQL messages that the extension's MessageConsumer receives.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 71 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_postgresql_mqtt_to_postgresql_(.+)_consumer_incoming_count\", __name__!=\"com_hivemq_extensions_postgresql_mqtt_to_postgresql_total_consumer_incoming_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_postgresql_mqtt_to_postgresql_(.+)_consumer_incoming_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{job}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to PostgreSQL in progress",
     "type": "timeseries",
     "description": "The current number of MQTT to PostgreSQL messages that are in the progress of being forwarded to PostgreSQL.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 71 },
     "targets": [
      {
       "expr": "label_replace({__name__=~\"com_hivemq_extensions_postgresql_mqtt_to_postgresql_(.+)_in_progress_count_current\", __name__!=\"com_hivemq_extensions_postgresql_mqtt_to_postgresql_total_in_progress_count_current\", __name__!~\"com_hivemq_extensions_postgresql_mqtt_to_postgresql_(.+)batches_in_progress_count_current\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_postgresql_mqtt_to_postgresql_(.+)_in_progress_count_current\")",
       "legendFormat": "{{job}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to PostgreSQL batches in progress",
     "type": "timeseries",
     "description": "The current number of MQTT to PostgreSQL batches that are in the progress of being forwarded to PostgreSQL.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "label_replace({__name__=~\"com_hivemq_extensions_postgresql_mqtt_to_postgresql_(.+)_batches_in_progress_count_current\", __name__!=\"com_hivemq_extensions_postgresql_mqtt_to_postgresql_total_batches_in_progress_count_current\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_postgresql_mqtt_to_postgresql_(.+)_batches_in_progress_count_current\")",
       "legendFormat": "{{job}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to PostgreSQL ${Route} Latency",
     "type": "timeseries",
     "description": "A histogram of the latency of all MQTT to PostgreSQL messages.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "com_hivemq_extensions_postgresql_mqtt_to_postgresql_${Route}_latency{namespace=~\"$namespace\"} * 1000",
       "legendFormat": "{{job}} {{quantile}} "
      }
     ]
    }
   ]
  },
  {
   "title": "HiveMQ Enterprise Extension for Snowflake",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "MQTT to Snowflake success/s",
     "type": "timeseries",
     "description": "The number of MQTT to Snowflake messages that the extension successfully forwards for each mqtt-to-snowflake-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 72 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_snowflake_mqtt_to_snowflake_(.+)_success_count\", __name__!=\"com_hivemq_extensions_snowflake_mqtt_to_snowflake_total_success_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_snowflake_mqtt_to_snowflake_(.+)_success_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to Snowflake failed/s",
     "type": "timeseries",
     "description": "The number of MQTT to Snowflake messages that the extension cannot successfully forward for each mqtt-to-snowflake-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 72 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_snowflake_mqtt_to_snowflake_(.+)_failed_count\", __name__!=\"com_hivemq_extensions_snowflake_mqtt_to_snowflake_total_failed_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_snowflake_mqtt_to_snowflake_(.+)_failed_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HiveMQ Enterprise Extension for Microsoft SQL Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "MQTT to MSSQL success/s",
     "type": "timeseries",
     "description": "The number of MQTT to MSSQL messages that the extension successfully forwards for each mqtt-to-mssql-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_mssql_mqtt_to_mssql_(.+)_success_count\", __name__!=\"com_hivemq_extensions_mssql_mqtt_to_mssql_total_success_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_mssql_mqtt_to_mssql_(.+)_success_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{job}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to MSSQL failed/s",
     "type": "timeseries",
     "description": "The number of MQTT to MSSQL messages that the extension cannot successfully forward for each mqtt-to-mssql-route, per second.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_mssql_mqtt_to_mssql_(.+)_failed_count\", __name__!=\"com_hivemq_extensions_mssql_mqtt_to_mssql_total_failed_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_mssql_mqtt_to_mssql_(.+)_failed_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{job}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to MSSQL consumer-incoming/s",
     "type": "timeseries",
     "description": "The number of MQTT to MSSQL messages that the extension's MessageConsumer receives.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "rate(label_replace({__name__=~\"com_hivemq_extensions_mssql_mqtt_to_mssql_(.+)_consumer_incoming_count\", __name__!=\"com_hivemq_extensions_mssql_mqtt_to_mssql_total_consumer_incoming_count\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_mssql_mqtt_to_mssql_(.+)_consumer_incoming_count\")[5m:${intervalSeconds}s])",
       "legendFormat": "{{job}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to MSSQL in progress",
     "type": "timeseries",
     "description": "The current number of MQTT to MSSQL messages that are in the progress of being forwarded to MSSQL.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
     "targets": [
      {
       "expr": "label_replace({__name__=~\"com_hivemq_extensions_mssql_mqtt_to_mssql_(.+)_in_progress_count_current\", __name__!=\"com_hivemq_extensions_mssql_mqtt_to_mssql_total_in_progress_count_current\", __name__!~\"com_hivemq_extensions_mssql_mqtt_to_mssql_(.+)batches_in_progress_count_current\", namespace=~\"$namespace\"}, \"route\", \"$1\", \"__name__\", \"com_hivemq_extensions_mssql_mqtt_to_mssql_(.+)_in_progress_count_current\")",
       "legendFormat": "{{job}} {{route}}"
      }
     ]
    },
    {
     "title": "MQTT to MSSQL ${Route} Latency",
     "type": "timeseries",
     "description": "A histogram of the latency of all MQTT to MSSQL messages.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "com_hivemq_extensions_mssql_mqtt_to_mssql_${Route}_latency{namespace=~\"$namespace\"} * 1000",
       "legendFormat": "{{job}} {{quantile}} "
      }
     ]
    }
   ]
  }
 ]
}