nodes:
  replicaCount: 1
additionalVolumes:
  - type: configMap
    name: test-configmap-volume
    mountName: test-mount-volume
    path: /additional-configmap-volume
    subPath: test.xml
  - type: secret
    name: test-secret-volume
    path: /additional-secret-volume
  - type: emptyDir
    name: test-empty-dir-volume
    path: /additional-empty-dir-volume
  - type: persistentVolumeClaim
    name: test-persistent-volume-claim
    path: /additional-persistent-volume-claim

