nodes:
  replicaCount: 1
  containerSecurityContext:
    runAsNonRoot: false
  env:
    - name: HIVEMQ_NO_ROOT_STEP_DOWN
      value: "true"
extensions:
  - name: hivemq-distributed-tracing-extension
    extensionUri: preinstalled
    enabled: true
    supportsHotReload: true
    configMapName: "distributed-tracing-configuration"
