nodes:
  replicaCount: 1
  sidecars:
    - name: consul-template
      image: hashicorp/consul-template:latest
      command: ["consul-template"]
      args: ["-config", "/consul-template/consul-template-sidecar.hcl", "-log-level", "debug", "-kill-signal", "SIGTERM"]
      volumeMounts:
        - name: license-volume
          mountPath: /opt/hivemq/license
        - name: consul-template-volume
          mountPath: /consul-template
additionalVolumes:
  - type: emptyDir
    name: license-volume
    containerName: hivemq
    path: /opt/hivemq/license
  - type: configMap
    name: consul-template-config-map
    mountName: consul-template-volume
    containerName: consul-template
  - type: emptyDir
    name: license-volume
    containerName: consul-template
