nodes:
  replicaCount: 1
services:
  - type: websocket
    exposed: true
    containerPort: 8002
  - type: websocket
    exposed: true
    containerPort: 8003
    keystoreSecretName: "ws-keystore-8003"
    keystorePassword: "a2V5c3RvcmUtcGFzc3dvcmQ=" # keystore-password
    keystorePrivatePassword: "cHJpdmF0ZS1rZXktcGFzc3dvcmQ=" # private-key-password
  - type: websocket
    exposed: true
    containerPort: 8004
    keystoreSecretName: "ws-keystore-8004"
    keystoreSecretKey: "keystore.jks"
    keystorePasswordSecretName: "ws-keystore-password-8004"
    keystorePrivatePasswordSecretKey: "my-private-key.password"
    truststoreSecretName: "ws-truststore-8004"
    truststorePasswordSecretName: "ws-truststore-password-8004"
    tlsClientAuthenticationMode: "REQUIRED"
