nodes:
  replicaCount: 1
services:
  - type: mqtt
    exposed: true
    containerPort: 1884
    keystoreSecretName: "mqtt-keystore-1884"
    keystoreSecretKey: "keystore.jks"
    keystorePassword: "a2V5c3RvcmUtcGFzc3dvcmQ=" # keystore-password
    keystorePrivatePassword: "cHJpdmF0ZS1rZXktcGFzc3dvcmQ=" # private-key-password
  - type: mqtt
    exposed: true
    containerPort: 1885
    keystoreSecretName: "mqtt-keystore-1885"
    keystoreSecretKey: "keystore.jks"
    keystorePasswordSecretName: "mqtt-keystore-password-1885"
    keystorePrivatePasswordSecretKey: "my-private-key.password"
  - type: mqtt
    exposed: true
    containerPort: 1886
