nodes:
  replicaCount: 1
services:
  - type: mqtt
    exposed: true
    containerPort: 1883
    keystoreSecretName: "mqtts-keystore"
    keystorePasswordSecretName: "mqtts-keystore-password"

  - type: mqtt
    exposed: true
    containerPort: 1884
    keystoreSecretName: "mqtts-keystore"
    keystoreSecretKey: "keystore.jks"
    keystorePasswordSecretName: "mqtts-keystore-password"
    tlsClientAuthenticationMode: "OPTIONAL"

  - type: control-center
    exposed: true
    containerPort: 8080
    keystoreSecretName: "https-keystore"
    keystorePasswordSecretName: "https-keystore-password"
