nodes:
  replicaCount: 1
services:
  - type: websocket
    exposed: true
    containerPort: 8002

  - type: websocket
    exposed: true
    containerPort: 8003
    keystoreSecretName: "ws-keystore-8003"
    keystorePassword: "a2V5LWNoYW5nZW1lCg=="
    truststoreSecretName: "ws-truststore-8003"
    truststoreSecretKey: "truststore.jks"
    truststorePassword: "dHJ1c3QtY2hhbmdlbWUK"

  - type: websocket
    exposed: true
    containerPort: 8004
    keystoreSecretName: "ws-keystore-8004"
    keystoreSecretKey: "keystore.jks"
    keystorePasswordSecretName: "ws-keystore-password-8004"
    truststoreSecretName: "ws-truststore-8004"
    truststorePasswordSecretName: "ws-truststore-password-8004"
    tlsClientAuthenticationMode: "REQUIRED"
