# Custom images Single node cluster with external mqtt port
operator:
  image: hivemq/hivemq-operator:snapshot
  imagePullPolicy: Never
  logLevel: DEBUG
  admissionWebhooks:
    enabled: false
monitoring:
  # Deploy ServiceMonitor for Prometheus Operator and enable Prometheus
  enabled: true

hivemq:
  image: hivemq/hivemq4-test:k8s-snapshot
  imagePullPolicy: Never
  initDnsWaitImage: hivemq/init-dns-wait:snapshot
  logLevel: DEBUG
  nodeCount: 1
  cpu: 1
  memory: 1Gi