{{- if and .Values.operator.admissionWebhooks.enabled .Values.operator.admissionWebhooks.patch.enabled .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  {{ template "hivemq.fullname" . }}-admission
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ include "hivemq.name" . }}-admission
{{ include "hivemq.labels" $ | indent 4 }}
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - get
      - update
{{- if .Values.global.rbac.pspEnabled }}
{{- $kubeTargetVersion := default .Capabilities.KubeVersion.GitVersion .Values.kubeTargetVersionOverride }}
{{- if semverCompare "> 1.15.0-0" $kubeTargetVersion }}
  - apiGroups: ['policy']
{{- else }}
  - apiGroups: ['extensions']
{{- end }}
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
    - {{ template "hivemq.fullname" . }}-admission
{{- end }}
{{- end }}
