{{- if and .Values.operator.admissionWebhooks.enabled .Values.operator.admissionWebhooks.patch.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ template "hivemq.fullname" . }}-admission-create
  namespace: {{ template "hivemq.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ include "hivemq.name" $ }}-admission-create
{{ include "hivemq.labels" $ | indent 4 }}
spec:
  {{- if .Capabilities.APIVersions.Has "batch/v1alpha1" }}
  # Alpha feature since k8s 1.12
  ttlSecondsAfterFinished: 0
  {{- end }}
  template:
    metadata:
      name:  {{ template "hivemq.fullname" . }}-admission-create
{{- with .Values.operator.admissionWebhooks.patch.podAnnotations }}
      annotations:
{{ toYaml .  | indent 8 }}
{{- end }}
      labels:
        app: {{ template "hivemq.name" $ }}-admission-create
{{ include "hivemq.labels" $ | indent 8 }}
    spec:
      {{- if .Values.operator.admissionWebhooks.patch.priorityClassName }}
      priorityClassName: {{ .Values.operator.admissionWebhooks.patch.priorityClassName }}
      {{- end }}
      containers:
        - name: create
          {{- if .Values.operator.admissionWebhooks.patch.image.sha }}
          image: {{ .Values.operator.admissionWebhooks.patch.image.repository }}:{{ .Values.operator.admissionWebhooks.patch.image.tag }}@sha256:{{ .Values.operator.admissionWebhooks.patch.image.sha }}
          {{- else }}
          image: {{ .Values.operator.admissionWebhooks.patch.image.repository }}:{{ .Values.operator.admissionWebhooks.patch.image.tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.operator.admissionWebhooks.patch.image.pullPolicy }}
          args:
            - create
            - --host={{ template "hivemq.fullname" . }}-operator,{{ template "hivemq.fullname" . }}-operator.{{ template "hivemq.namespace" . }}.svc
            - --namespace={{ template "hivemq.namespace" . }}
            - --secret-name={{ template "hivemq.fullname" . }}-admission
          resources:
{{ toYaml .Values.operator.admissionWebhooks.patch.resources | indent 12 }}
      restartPolicy: OnFailure
      serviceAccountName: {{ template "hivemq.fullname" . }}-admission
      {{- with .Values.operator.admissionWebhooks.patch.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.operator.admissionWebhooks.patch.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.operator.admissionWebhooks.patch.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      securityContext:
{{ toYaml .Values.global.rbac.securityContext | indent 8 }}
{{- end }}
