{{- if and (.Values.license.create) (.Values.license.enabled)}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "hivemq-edge.labels" . | nindent 4 }}
  name: {{ include "hivemq-edge.name" (dict "prefix" "hivemq-edge" "name" "license" "releaseName" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  license.edgelic: |
    {{- .Files.Get "files/license.edgelic" | b64enc | nindent 4 }}
{{- end }}
