{{- if not .Values.admin.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "hivemq-edge.labels" . | nindent 4 }}
  name: {{ include "hivemq-edge.name" (dict "prefix" "hivemq-edge" "name" "admin" "releaseName" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  user: {{ .Values.admin.user | b64enc }}
  password: {{ .Values.admin.password | b64enc }}
{{- end }}
