{{- if and (.Values.mqttsClientauth.create.enabled) (.Values.mqtts.mqttsClientauth.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "hivemq-edge.labels" . | nindent 4 }}
  name: {{ include "hivemq-edge.name" (dict "prefix" "hivemq-edge" "name" "clientauth" "releaseName" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  truststore-password: {{ .Values.mqttsClientauth.create.truststorePassword | b64enc }}
  truststore.jks: |
    {{ .Values.mqttsClientauth.create.file | b64enc | nindent 4}}
{{- end }}
