apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-template-config-map
data:
  consul-template-sidecar.hcl: |
    template {
      source      = "/consul-template/license.lic"
      destination = "/opt/hivemq/license/license.lic"
    }
  license.lic: |
    Brc979+n_zC2c88rS-eUZC7wNm6jyb==r4dy.6Z6+B=-%3emB9b*?HRFY{X)R?B#bC]T2Eq:T7P$].3}[Yn}?r}VK:whBzt[GeumdDJ43F;dmAKbU2v#
    qLXG@jrx,ri[%QVe((JXc__k@K=tqxdTP=NwX?JB*xwdf}9Zy7NXWb$jQJ6c3j2DKP(TW#68&p)#99{J;=ERg:wNq;bz$*Qy%@MT/)2z(eM,jX2tHa,=!N{NbYq:R[u=G
    &xcjSX8S)ZUTTeRM}@TuntV2.VSK%FrwSh%e]j7pidKw]Sa!u7+]LwF,]wK*RLw)g(c;w-g*S#;z}cMjxDmwrWYhh6?zTkU9{BJgBn+A(eCuvX]+mvT@K95Nvm-6xCSCN}haq}*]TR
    }rxp/6{f&*.pn];vMRb?4)@&7&T.k}D)UJg[Q7&Kun&2zSrJVM(/iYKBzW/d-jHGkZh?mM:u6mBVnj)(N%ex)C#=fd.Ug9+-ejt]L;6je@+PNj5++=H;w{gG[SKS]e//!/7P9nx8r/
    RkB#n$,Kr*J(;J2LpHiA:Wgw4b7!P=hQ/C$QX;{[M(eS446J_(CAwb_hENx[/L8jU]y.TrZD:iNN_X4wAint@=}/8wxy_xz/$t.#ChDy8Pd@pjYdnqR/y.P6C-fdhg:(TAB$Fgm:G+ar,LW8777
    KxE:/-dzP.r==gZNVy9N:5#]wPk)RvLf5m-F3tc!;3nh@hR9/zP:)&cZcPd7K/b5WKnHACGmb#YygELDb]hw88}kN.GCC#}+fx%Xr;F/[c)QJyTDY&_BkrLKuzqjNnxG=.N_6U#[u8bgfJpT6AD(k
    @H#Mx5dVP8r(D]h.CcrGM/c#gbR@!M/YR_gpQ-)*3:DbvajRmtTGrxRe%7_jJia%_x_r/fp(n+j_nd=E-WYg9R[p#mu5&i65*FEB*)[kg!j5P}HqS+Kc{qV}Kp3u}KXLJq#)g!S-UJ8U+wZu:V;@
    @eKT8}T;?dcehe=)yS:C54e75]exQVp$PWy4{aHrpX:p=bDFev/Lr/Wz&w*X3D]V;6hc}cb$#jtk8BzErRNTP[W8mak}/u6$.RKzvCLmt#d+E.@g_wd!x}/WmZ2Z9)}AtS5]PJWHfY!cKhLcSz:H
    Jzja}}E;HDJS9&6,;hi=9.dPWFh4qHa5,WdX$!SCuJ[{%xweu/tc$K5jr8V:KcSaQ&zgQPAtdk2Qd2QJzcHPfq89KR@k+}7j]/x5+Eg;e/yu,U+W)!)mq-58FBXu25qa$(yV5f(iQ(@&irHpBaS
