apiVersion: v1
kind: ConfigMap
metadata:
  name: hivemq-configuration-test-hivemq-platform
data:
  config.xml: |
    <?xml version="1.0"?>
    <hivemq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">
      <listeners>
        <tcp-listener>
          <port>1884</port>
          <bind-address>0.0.0.0</bind-address>
        </tcp-listener>
      </listeners>
      <cluster>
        <transport>
          <tcp>
            <bind-address>0.0.0.0</bind-address>
            <bind-port>7000</bind-port>
          </tcp>
        </transport>
        <enabled>true</enabled>
        <discovery>
          <extension/>
        </discovery>
      </cluster>
      <!-- required and should not be configured different -->
      <health-api>
        <enabled>true</enabled>
        <listeners>
          <http>
            <port>8889</port>
            <bind-address>0.0.0.0</bind-address>
          </http>
        </listeners>
      </health-api>
      <control-center>
        <listeners>
          <http>
            <port>8080</port>
            <bind-address>0.0.0.0</bind-address>
          </http>
        </listeners>
      </control-center>
      <anonymous-usage-statistics>
        <enabled>false</enabled>
      </anonymous-usage-statistics>
      <restrictions>
        <max-connections>-1</max-connections>
        <incoming-bandwidth-throttling>0</incoming-bandwidth-throttling>
        <no-connect-idle-timeout>10000</no-connect-idle-timeout>
        <max-client-id-length>65535</max-client-id-length>
      </restrictions>
      <mqtt>
        <session-expiry>
          <max-interval>4294967295</max-interval>
        </session-expiry>
        <message-expiry>
          <max-interval>4294967296</max-interval>
        </message-expiry>
        <packets>
          <max-packet-size>268435460</max-packet-size>
        </packets>
        <receive-maximum>
          <server-receive-maximum>10</server-receive-maximum>
        </receive-maximum>
        <keep-alive>
          <max-keep-alive>65535</max-keep-alive>
          <allow-unlimited>true</allow-unlimited>
        </keep-alive>
        <topic-alias>
          <enabled>true</enabled>
          <max-per-client>5</max-per-client>
        </topic-alias>
        <subscription-identifier>
          <enabled>true</enabled>
        </subscription-identifier>
        <wildcard-subscriptions>
          <enabled>true</enabled>
        </wildcard-subscriptions>
        <shared-subscriptions>
          <enabled>true</enabled>
        </shared-subscriptions>
        <quality-of-service>
          <max-qos>2</max-qos>
        </quality-of-service>
        <retained-messages>
          <enabled>true</enabled>
        </retained-messages>
        <queued-messages>
          <max-queue-size>1000</max-queue-size>
          <strategy>discard</strategy>
        </queued-messages>
      </mqtt>
      <mqtt-addons>
        <expired-messages-topic>
          <enabled>false</enabled>
        </expired-messages-topic>
        <dropped-messages-topic>
          <enabled>false</enabled>
        </dropped-messages-topic>
        <dead-messages-topic>
          <enabled>false</enabled>
        </dead-messages-topic>
      </mqtt-addons>
      <security>
        <allow-empty-client-id>
          <enabled>true</enabled>
        </allow-empty-client-id>
        <payload-format-validation>
          <enabled>false</enabled>
        </payload-format-validation>
        <utf8-validation>
          <enabled>true</enabled>
        </utf8-validation>
        <allow-request-problem-information>
          <enabled>true</enabled>
        </allow-request-problem-information>
        <control-center-audit-log>
          <enabled>true</enabled>
        </control-center-audit-log>
      </security>
    </hivemq>
