{{- if .Values.config.create }}
apiVersion: v1
kind: {{ ternary "Secret" "ConfigMap" .Values.config.useSecret }}
metadata:
  name: {{ include "hivemq-platform.configuration-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hivemq-platform.labels" . | nindent 4 }}
data:
  # noinspection XmlPathReference
  config.xml: |-
    {{- include "hivemq-platform.generate-hivemq-configuration" . }}
  tracing.xml: |-
    {{- include "hivemq-platform.generate-hivemq-tracing-configuration" . }}
  {{- if .Values.config.customLogbackConfig }}
  logback.xml: |-
    {{- include "hivemq-platform.generate-hivemq-logback-configuration" . }}
  {{- end }}
{{- end }}
