{{- if .Values.config.create }}
apiVersion: v1
kind: {{ .Values.config.createAs }}
metadata:
  name: {{ include "hivemq-platform.configuration-name" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "hivemq-platform.labels" . | nindent 4 }}
    {{- with .Values.config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  # noinspection XmlPathReference
  config.xml: |-
    {{- include "hivemq-platform.generate-hivemq-configuration" . }}
  tracing.xml: |-
    {{- include "hivemq-platform.generate-hivemq-tracing-configuration" . }}
  logback.xml: |-
    <configuration scan="false">

    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
    <pattern>%-30(%d %level)- %msg%n%ex</pattern>
    </encoder>
    </appender>

    <logger name="migrations" level="INFO" additivity="false">
    <appender-ref ref="CONSOLE"/>
    </logger>

    <root level="TRACE">
    <appender-ref ref="CONSOLE"/>
    </root>

    <logger name="jetbrains.exodus" level="TRACE"/>
    <logger name="org.eclipse.jetty" level="ERROR"/>
    <logger name="com.google.common.util.concurrent.Futures.CombinedFuture" level="OFF"/>
    <logger name="oshi" level="ERROR"/>
    <logger name="org.jgroups" level="DEBUG"/>
    <logger name="org.jboss.logging" level="WARN"/>
    <logger name="org.jboss.resteasy" level="WARN"/>
    <logger name="com.networknt" level="WARN"/>

    <logger name="org.rocksdb" level="TRACE"/>

    </configuration>
{{- end }}
