env:
  - name: HIVEMQ_CONFIG_WRITEABLE
    value: "false"
  - name: HIVEMQ_LOG_LEVEL
    value: "INFO"
  - name: JAVA_OPTS
    value: "-XX:+UnlockExperimentalVMOptions -XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75"
  - name: HIVEMQ_LICENSE_FOLDER
    value: "/license.edgelic"
  - name: HIVEMQ_DATA_FOLDER
    value: "/persistence"
  - name: HIVEMQ_CONFIG_FOLDER
    value: "/opt/hivemq/conf-k8s"
  - name: HIVEMQ_CONFIG_REFRESHINTERVAL
    value: "1000"
  - name: HIVEMQ_PERSISTENCE_MODE
    value: "in-memory"
  - name: HIVEMQ_MQTT_ENABLED
    value: "true"
  - name: HIVEMQ_MQTTS_ENABLED
    value: "true"
  - name: HIVEMQ_MQTTS_CLIENT_AUTH_MODE
    value: "NONE"
  - name: HIVEMQ_MQTTS_PREFER_SERVER_CIPHER_SUITE
    value: "false"
  - name: HIVEMQ_MQTTS_KEYSTORE_PATH
    value: /mqtts/keystore.jks
  - name: HIVEMQ_MQTTS_SECRET_KEYSTORE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "hivemq-keystore-secret"
        key: "keystore-password"
  - name: HIVEMQ_MQTTS_SECRET_PRIVATE_KEY_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "hivemq-keystore-secret"
        key: "secret-key-password"
  - name: HIVEMQ_ADMIN_USER
    valueFrom:
      secretKeyRef:
        name: "hivemq-edge-admin-edge"
        key: user
  - name: HIVEMQ_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "hivemq-edge-admin-edge"
        key: password
resources:
  limits:
    memory: "1Gi"
    cpu: "1000m"
  requests:
    memory: "1Gi"
    cpu: "1000m"
volumeMounts:
  - name: fragment
    mountPath: /fragment
  - mountPath: /mqtts
    name: mqtts-jks
  - mountPath: /license.edgelic
    name: license
volumes:
  - name: fragment
    configMap:
      name: hivemq-edge-config-edge
  - name: mqtts-jks
    secret:
      secretName: "hivemq-keystore-secret"
      items:
        - key: "keystore.jks"
          path: "keystore.jks"
