{{- if .Values.serviceAccount.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "hivemq-platform-operator-view-{{.Release.Name}}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: {{ include "hivemq-platform-operator.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "hivemq-platform-operator-role-binding-{{.Release.Name}}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: "hivemq-platform-operator-role-{{.Release.Name}}"
subjects:
  - kind: ServiceAccount
    name: {{ include "hivemq-platform-operator.serviceAccountName" . }}
    namespace: {{.Release.Namespace}}
---
{{- end }}
