{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hivemq-platform-operator.serviceAccountName" . }}
  labels:
    {{- include "hivemq-platform-operator.labels" . | nindent 4 }}
{{- end }}
