{{- if .Values.monitoring.enabled }}
{{- include "hivemq-swarm.validate-prometheus-monitoring-stack-installed" . -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "hivemq-swarm.labels" . | nindent 4 }}
    release: {{ .Values.monitoring.serviceMonitor.releaseName | default .Release.Name }}
  name: {{ include "hivemq-swarm.fullname" . }}
  {{- if .Values.monitoring.serviceMonitor.namespace }}
  namespace: {{ .Values.monitoring.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ template "hivemq-swarm.namespace" . }}
  {{- end }}
spec:
  endpoints:
    - interval: {{ .Values.monitoring.serviceMonitor.interval }}
      {{- if .Values.monitoring.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      {{- end }}
      port: api
    - interval: {{ .Values.monitoring.serviceMonitor.interval }}
      {{- if .Values.monitoring.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      {{- end }}
      port: metrics
  jobLabel: {{ include "hivemq-swarm.fullname" . }}
  selector:
    matchLabels:
      {{- include "hivemq-swarm.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
