apiVersion: v1
kind: Service
metadata:
  name: {{ include "hivemq-swarm.fullname" . }}-api
  namespace: {{ template "hivemq-swarm.namespace" . }}
  labels:
    hivemq.com/swarm-role: commander
    {{- include "hivemq-swarm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: api
      {{- if and (.Values.service.nodePort) (eq (.Values.service.type | toString) "NodePort") }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    hivemq.com/swarm-role: commander
    {{- include "hivemq-swarm.selectorLabels" . | nindent 4 }}
