{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hivemq-swarm.serviceAccountName" . }}
  namespace: {{ template "hivemq-swarm.namespace" . }}
  labels:
    {{- include "hivemq-swarm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
