apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-template-config-map
data:
  consul-template.hcl: |
    template {
      source      = "/consul-template/license.lic"
      destination = "/opt/hivemq/license/license.lic"
    }
  license.lic: |
    This is an invalid license
