name: Verify
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3
        with:
          # only needed if the version is 'latest'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: |
          helm lint ./charts/hivemq-platform
          helm lint ./charts/hivemq-platform-operator
          helm lint ./charts/hivemq-operator
          helm lint ./charts/hivemq-swarm
      - name: Unit Test
        uses: d3adb5/helm-unittest-action@66140cd099aa6c4f2ebc59735b8e421135a6d4e3 # v2.4
        with:
          helm-version: v3.10.1
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check manifests are up-to-date
        run: |
          ./manifests/hivemq-operator/manifests.sh
          ./manifests/hivemq-platform-operator/manifests.sh
          ./manifests/hivemq-platform/manifests.sh
          ./manifests/hivemq-swarm/manifests.sh
          git diff HEAD --exit-code
