name: Verify
on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
concurrency:
  group: verify-${{ github.ref }}
  cancel-in-progress: true
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HiveMQ Helm Charts
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4

      - name: Set up Kubeconform
        run: |
          helm plugin install https://github.com/jtyr/kubeconform-helm

      - name: Add Prometheus dependency Helm chart repo
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

      - name: Update HiveMQ legacy Operator chart dependencies
        run: |
          helm dependency update charts/hivemq-operator

      - name: Lint
        if: always()
        run: |
          helm lint charts/hivemq-edge
          helm lint charts/hivemq-operator
          helm lint charts/hivemq-platform
          helm lint charts/hivemq-platform-operator
          helm lint charts/hivemq-swarm

      - name: Unit Test
        if: always()
        uses: d3adb5/helm-unittest-action@66140cd099aa6c4f2ebc59735b8e421135a6d4e3 # v2.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flags: --file './tests/**/*_test.yaml'

      - name: Check manifests are up-to-date
        if: always()
        run: |
          manifests/hivemq-edge/manifests.sh
          manifests/hivemq-operator/manifests.sh
          manifests/hivemq-platform/manifests.sh
          manifests/hivemq-platform-operator/manifests.sh
          manifests/hivemq-swarm/manifests.sh
          git add manifests/ -v
          git diff HEAD --exit-code

      - name: Parse HiveMQ CRDs from OpenAPI to JSON schema
        if: always()
        run: |
          export FILENAME_FORMAT='{kind}.{group}-{version}'
          .github/openapi2jsonschema.py charts/hivemq-operator/crds/hivemq-cluster.yaml
          .github/openapi2jsonschema.py charts/hivemq-platform-operator/crds/hivemq-platforms.hivemq.com-v1.yml

      - name: Validate rendered manifests
        if: always()
        run: |
          helm kubeconform --config .github/configs/kubeconform.yml charts/hivemq-edge -r hivemq-edge-release -n hivemq-edge-namespace
          helm kubeconform --config .github/configs/kubeconform.yml charts/hivemq-operator -r hivemq-operator-release -n hivemq-operator-namespace --schema-location hivemqcluster.hivemq-v1.json
          helm kubeconform --config .github/configs/kubeconform.yml charts/hivemq-platform -r hivemq-platform-release -n hivemq-platform-namespace --schema-location hivemqplatform.hivemq-v1.json
          helm kubeconform --config .github/configs/kubeconform.yml charts/hivemq-platform-operator -r hivemq-platform-operator-release -n hivemq-platform-operator-namespace
          helm kubeconform --config .github/configs/kubeconform.yml charts/hivemq-swarm -r hivemq-swarm-release -n hivemq-swarm-namespace

      - name: Validate branch protection
        if: always()
        env:
          GH_TOKEN: ${{ secrets.JENKINS_GITHUB_TOKEN }}
        run: bash ./scripts/validate-branch-protection.sh ${{ github.base_ref }}
