name: Verify
on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HiveMQ Helm Charts
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Set up Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4

      - name: Add dependency chart repos
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

      - name: Update chart dependencies
        run: |
          helm dependency update ./charts/hivemq-platform
          helm dependency update ./charts/hivemq-platform-operator
          helm dependency update ./charts/hivemq-operator
          helm dependency update ./charts/hivemq-swarm

      - name: Lint
        run: |
          helm lint ./charts/hivemq-platform
          helm lint ./charts/hivemq-platform-operator
          helm lint ./charts/hivemq-operator
          helm lint ./charts/hivemq-swarm

      - name: Unit Test
        uses: d3adb5/helm-unittest-action@66140cd099aa6c4f2ebc59735b8e421135a6d4e3 # v2.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check manifests are up-to-date
        run: |
          ./manifests/hivemq-operator/manifests.sh
          ./manifests/hivemq-platform-operator/manifests.sh
          ./manifests/hivemq-platform/manifests.sh
          ./manifests/hivemq-swarm/manifests.sh
          git diff HEAD --exit-code
